### ISSUE TITLE
Can't center header title

### ISSUE THREAD

**Issue by Villeloso** [fossifation/guion#5]
Using react-native and react-navigation, for some reason nothing I tried worked to center the title.
Exemples of attempts:

1-AlignSelf

export default class First extends React.Component {
    static navigationOptions = {
        title: 'Start',
        headerStyle: {
            backgroundColor: '#000080',
        },
        headerTintColor: '#ffffff',
        headerTitleStyle: {
            fontWeight: 'bold',
            fontSize: 20,
            alignSelf: 'center',
        },
    }

2-TextAlign

export default class First extends React.Component {
    static navigationOptions = {
        title: 'Start',
        headerStyle: {
            backgroundColor: '#000080',
        },
        headerTintColor: '#ffffff',
        headerTitleStyle: {
            fontWeight: 'bold',
            fontSize: 20,
            textAlign: 'center',
        },
    }

3-Both

export default class First extends React.Component {
    static navigationOptions = {
        title: 'Start',
        headerStyle: {
            backgroundColor: '#000080',
        },
        headerTintColor: '#ffffff',
        headerTitleStyle: {
            fontWeight: 'bold',
            fontSize: 20,
            alignSelf: 'center',
            textAlign: 'center',
        },
    }

Even tried usinng empty headerRight/headerLeft, but nothing happens.

**Comment by mrwanashraf** [comment]
Thanks for your concern regarding contributing to guion however we are at the very early stage of development for guion plus the project is already on hold.

lastly this project is not targeting mobile devices, thus there is no need for react native.

i will go ahead and close the issue since its not relevant to the project.
